import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Building,
  CheckSquare,
  BarChart3,
  BookOpen,
  DollarSign,
  Wallet,
  Smartphone,
  ClipboardList,
  FileText,
  ScrollText,
  Scale,
  Bus,
  MessageSquare,
  Calendar,
  FileBarChart,
  TrendingUp,
  Search,
  Lock,
  User,
  Library,
  Megaphone,
  PenTool,
  FolderOpen,
  FileEdit,
  FileSpreadsheet,
  FilePieChart,
  Settings,
  FileCheck,
  Printer,
  CreditCard,
  Receipt,
  Shield,
  Bell,
  Home,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Minus,
  Search as SearchIcon,
  Filter,
  MoreVertical,
  Edit,
  Trash2,
  Download,
  Upload,
  RefreshCw,
  Eye,
  EyeOff,
  Check,
  XCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Clock,
  CalendarDays,
  UserPlus,
  UserMinus,
  Mail,
  Phone,
  MapPin,
  Globe,
  Link,
  Copy,
  ExternalLink,
  Star,
  StarOff,
  Heart,
  HeartOff,
  Bookmark,
  BookmarkCheck,
  Archive,
  ArchiveRestore,
  Share2,
  Printer as PrinterIcon,
  Save,
  Undo,
  Redo,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Fullscreen,
  ExitFullscreen,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Camera,
  CameraOff,
  Image,
  Film,
  Music,
  Radio,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  Snowflake,
  Flame,
  Zap,
  Cpu,
  HardDrive,
  Database,
  Server,
  Network,
  Globe as GlobeIcon,
  Navigation,
  Compass,
  Map,
  Locate,
  LocateFixed,
  Crosshair,
  Target,
  Ruler,
  Pencil,
  Eraser,
  Highlighter,
  Pen,
  Paintbrush,
  Palette,
  Scissors,
  Paperclip,
  Link2,
  Unlink,
  Hash,
  AtSign,
  Percent,
  DollarSign as DollarIcon,
  Euro,
  PoundSterling,
  Yen,
  Bitcoin,
  CreditCard as CreditCardIcon,
  Banknote,
  Coins,
  PiggyBank,
  Wallet as WalletIcon,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  Move,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  Expand,
  Shrink,
  Maximize2,
  Minimize2,
  Crop,
  Scan,
  QrCode,
  Barcode,
  Fingerprint,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldQuestion,
  LockOpen,
  Key,
  KeyRound,
  Fingerprint as FingerprintIcon,
  UserCheck,
  UserX,
  UserCircle,
  UserSquare,
  Users as UsersIcon,
  UserCog,
  UserMinus as UserMinusIcon,
  UserPlus as UserPlusIcon,
  UsersRound,
  Crown,
  Medal,
  Award,
  Trophy,
  Gift,
  Cake,
  Candle,
  Sparkles,
  Star as StarIcon,
  StarHalf,
  Zap as ZapIcon,
  Flame as FlameIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudSun,
  CloudMoon,
  Snowflake as SnowflakeIcon,
  Thermometer as ThermometerIcon,
  Droplets as DropletsIcon,
  Wind as WindIcon,
  Umbrella as UmbrellaIcon,
  Flame as FlameIcon,
  Zap as ZapIcon,
  Cpu as CpuIcon,
  HardDrive as HardDriveIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Network as NetworkIcon,
  Globe as GlobeIcon,
  Navigation as NavigationIcon,
  Compass as CompassIcon,
  Map as MapIcon,
  Locate as LocateIcon,
  LocateFixed as LocateFixedIcon,
  Crosshair as CrosshairIcon,
  Target as TargetIcon,
  Ruler as RulerIcon,
  Pencil as PencilIcon,
  Eraser as EraserIcon,
  Highlighter as HighlighterIcon,
  Pen as PenIcon,
  Paintbrush as PaintbrushIcon,
  Palette as PaletteIcon,
  Scissors as ScissorsIcon,
  Paperclip as PaperclipIcon,
  Link2 as Link2Icon,
  Unlink as UnlinkIcon,
  Hash as HashIcon,
  AtSign as AtSignIcon,
  Percent as PercentIcon,
  DollarSign as DollarSignIcon,
  Euro as EuroIcon,
  PoundSterling as PoundSterlingIcon,
  Yen as YenIcon,
  Bitcoin as BitcoinIcon,
  CreditCard as CreditCardIcon,
  Banknote as BanknoteIcon,
  Coins as CoinsIcon,
  PiggyBank as PiggyBankIcon,
  Wallet as WalletIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpRight as ArrowUpRightIcon,
  ArrowUpLeft as ArrowUpLeftIcon,
  ArrowDownRight as ArrowDownRightIcon,
  ArrowDownLeft as ArrowDownLeftIcon,
  ArrowUpCircle as ArrowUpCircleIcon,
  ArrowDownCircle as ArrowDownCircleIcon,
  ArrowLeftCircle as ArrowLeftCircleIcon,
  ArrowRightCircle as ArrowRightCircleIcon,
  ChevronsUp as ChevronsUpIcon,
  ChevronsDown as ChevronsDownIcon,
  ChevronsLeft as ChevronsLeftIcon,
  ChevronsRight as ChevronsRightIcon,
  CornerUpLeft as CornerUpLeftIcon,
  CornerUpRight as CornerUpRightIcon,
  CornerDownLeft as CornerDownLeftIcon,
  CornerDownRight as CornerDownRightIcon,
  Move as MoveIcon,
  MoveUp as MoveUpIcon,
  MoveDown as MoveDownIcon,
  MoveLeft as MoveLeftIcon,
  MoveRight as MoveRightIcon,
  Expand as ExpandIcon,
  Shrink as ShrinkIcon,
  Maximize2 as Maximize2Icon,
  Minimize2 as Minimize2Icon,
  Crop as CropIcon,
  Scan as ScanIcon,
  QrCode as QrCodeIcon,
  Barcode as BarcodeIcon,
  Fingerprint as FingerprintIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldAlert as ShieldAlertIcon,
  ShieldX as ShieldXIcon,
  ShieldQuestion as ShieldQuestionIcon,
  LockOpen as LockOpenIcon,
  Key as KeyIcon,
  KeyRound as KeyRoundIcon,
  Fingerprint as FingerprintIcon,
  UserCheck as UserCheckIcon,
  UserX as UserXIcon,
  UserCircle as UserCircleIcon,
  UserSquare as UserSquareIcon,
  Users as UsersIcon,
  UserCog as UserCogIcon,
  UserMinus as UserMinusIcon,
  UserPlus as UserPlusIcon,
  UsersRound as UsersRoundIcon,
  Crown as CrownIcon,
  Medal as MedalIcon,
  Award as AwardIcon,
  Trophy as TrophyIcon,
  Gift as GiftIcon,
  Cake as CakeIcon,
  Candle as CandleIcon,
  Sparkles as SparklesIcon,
  Star as StarIcon,
  StarHalf as StarHalfIcon,
} from 'lucide-react';

// Emoji to Lucide React icon mapping
export const EMOJI_TO_ICON = {
  // Dashboard & Analytics
  '\u{1F4CA}': BarChart3, // 📊 - Dashboard, Grades, Reports, Chart of Accounts, Balance Sheet
  '\u{1F4C8}': FileBarChart, // 📈 - Analytics, Income Statement
  
  // People
  '\u{1F465}': Users, // 👥 - Students
  '\u{1F9D1}\u200D\u{1F3EB}': GraduationCap, // 🧑‍🏫 - Teachers
  '\u{1F3EB}': Building, // 🏫 - Staff
  '\u{1F9D1}': User, // 🧑 - HR
  
  // Actions & Status
  '\u2714': CheckSquare, // ✔ - Attendance
  '\u2696': Scale, // ⚖️ - Discipline, Trial Balance
  
  // Content & Documents
  '\u{1F4D6}': BookOpen, // 📖 - Subjects, General Ledger
  '\u{1F4CB}': ClipboardList, // 📋 - Admissions
  '\u{1F4C4}': ScrollText, // 📄 - Report Cards
  '\u{1F4DD}': PenTool, // 📝 - Exams, Update Requests, Journal Entries, Lesson Plans
  
  // Finance
  '\u{1F4B3}': DollarSign, // 💳 - Fees
  '\u{1F4B8}': Wallet, // 💸 - Expenditures
  '\u{1F4F2}': Smartphone, // 📲 - M-Pesa Reconcile
  '\u{1F9FE}': CreditCard, // 🧾 - Invoices
  '\u{1F4B0}': TrendingUp, // 💰 - Financial Reports
  
  // Communication
  '\u{1F4AC}': MessageSquare, // 💬 - Communication
  
  // Time & Planning
  '\u{1F5D3}': Calendar, // 🗓️ - Timetable
  
  // Search & Analysis
  '\u{1F50D}': Search, // 🔍 - Analysis
  
  // Security & Access
  '\u{1F511}': Lock, // 🔒 - Accounts
  
  // Library
  '\u{1F4DA}': Library, // 📚 - Library
  
  // Announcements
  '\u{1F4E2}': Megaphone, // 📢 - Announcements
  
  // Files & Import/Export
  '\u{1F4C1}': FolderOpen, // 📁 - Import/Export
  
  // Settings
  '\u2699': Settings, // ⚙️ - Settings
};

// Fallback icon for unmapped emojis
export const DEFAULT_ICON = LayoutDashboard;

// Get Lucide icon component from emoji
export function getIconFromEmoji(emoji) {
  return EMOJI_TO_ICON[emoji] || DEFAULT_ICON;
}

// Get icon component by page ID
export function getIconByPageId(pageId) {
  const navItem = [...NAV, ...NAV_EXTRAS].find(item => item.id === pageId);
  return navItem ? getIconFromEmoji(navItem.icon) : DEFAULT_ICON;
}

// Re-export NAV and NAV_EXTRAS for convenience
export { NAV, NAV_EXTRAS } from './constants.js';
