name: EduCore Local
values:
  - key: baseUrl
    value: 'http://localhost:4000'
    type: default
    enabled: true
  - key: token
    value: ''
    type: secret
    enabled: true
  - key: schoolId
    value: '1'
    type: default
    enabled: true
  - key: paystackSecretKey
    value: 'sk_test_a4fa82fd12af8908730545b08ba6ca2aae2d676a'
    type: secret
    enabled: true
  - key: atApiKey
    value: 'atsk_e6126188f3be2fe6bea26d00b0cae479739c3ed752e10216dd79b030c9acf24225b1f983'
    type: secret
    enabled: true
  - key: atUsername
    value: 'sandbox'
    type: default
    enabled: true
  - key: paymentReference
    value: ''
    type: default
    enabled: true
  - key: studentId
    value: '1'
    type: default
    enabled: true
