-- EduCore Postgres/Supabase schema
-- Creates ONLY the `lesson_plans` table.
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - LONGTEXT/TEXT -> TEXT
-- - DATETIME -> TIMESTAMPTZ
-- - TINYINT UNSIGNED -> SMALLINT (we add a 0..100 check for ai_score)
-- - `updated_at ON UPDATE` is not automatic in Postgres.

DO $$
BEGIN
  CREATE TYPE public.lesson_plan_type AS ENUM ('lesson_plan','scheme');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.lesson_plan_status AS ENUM ('draft','pending','approved','rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.lesson_plans (
  plan_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          BIGINT NOT NULL REFERENCES public.schools(school_id),
  teacher_id         BIGINT NOT NULL REFERENCES public.users(user_id),
  type               public.lesson_plan_type NOT NULL DEFAULT 'lesson_plan',

  subject            VARCHAR(80)  NOT NULL,
  class_name          VARCHAR(40)  NOT NULL,
  term               VARCHAR(20)  NOT NULL,
  week               VARCHAR(10)  NULL,
  topic              VARCHAR(160) NOT NULL,
  duration           VARCHAR(30)  NULL,

  content            TEXT NOT NULL,

  ai_score           SMALLINT NULL CHECK (ai_score IS NULL OR (ai_score >= 0 AND ai_score <= 100)),
  ai_missing         TEXT NULL,
  ai_weak            TEXT NULL,
  ai_recommendations TEXT NULL,
  ai_feedback_draft  TEXT NULL,

  status             public.lesson_plan_status NOT NULL DEFAULT 'draft',
  admin_feedback     TEXT NULL,
  reviewed_by        BIGINT NULL REFERENCES public.users(user_id),
  reviewed_at        TIMESTAMPTZ NULL,

  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_deleted         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_lesson_plans_school_status ON public.lesson_plans (school_id, status);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_teacher       ON public.lesson_plans (teacher_id);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_school_type   ON public.lesson_plans (school_id, type);

