-- EduCore Postgres/Supabase schema
-- Creates ONLY the `attendance` table (depends on `schools`, `students`, `classes`, `users`).

DO $$
BEGIN
  CREATE TYPE public.attendance_status AS ENUM ('present','absent','late');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.attendance (
  attendance_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id        BIGINT NOT NULL REFERENCES public.students(student_id),
  class_id          BIGINT NOT NULL REFERENCES public.classes(class_id),
  attendance_date   DATE NOT NULL,
  status            public.attendance_status NOT NULL,
  marked_by_user_id BIGINT NULL REFERENCES public.users(user_id),
  remarks           VARCHAR(255) NULL,
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_student_date
  ON public.attendance (school_id, student_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendance_school_class_date
  ON public.attendance (school_id, class_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendance_deleted
  ON public.attendance (is_deleted);

