-- EduCore Postgres/Supabase schema (Step 2)
-- This file creates ONLY the `schools` table so we can migrate one table at a time.
--
-- Run in Supabase SQL editor (or psql).
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - TINYINT(1) -> boolean
-- - `updated_at ON UPDATE` is not automatic in Postgres; app already sets updated_at in UPDATEs.

DO $$
BEGIN
  CREATE TYPE public.subscription_status AS ENUM ('active','inactive','trial');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.schools (
  school_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                VARCHAR(160) NOT NULL,
  code                VARCHAR(40)  NOT NULL UNIQUE,
  email               VARCHAR(160) NULL,
  phone               VARCHAR(40)  NULL,
  address             VARCHAR(255) NULL,
  county              VARCHAR(120) NULL,
  country             VARCHAR(120) NOT NULL DEFAULT 'Kenya',
  subscription_status public.subscription_status NOT NULL DEFAULT 'trial',
  subscription_start  DATE NULL,
  subscription_end    DATE NULL,
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_schools_status  ON public.schools (subscription_status);
CREATE INDEX IF NOT EXISTS idx_schools_deleted ON public.schools (is_deleted);

