-- EduCore Postgres/Supabase schema
-- Creates ONLY the `sms_logs` table (depends on `schools`, `users`).

DO $$
BEGIN
  CREATE TYPE public.comm_channel AS ENUM ('sms','email','push');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.comm_status AS ENUM ('queued','sent','failed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.sms_logs (
  sms_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         BIGINT NOT NULL REFERENCES public.schools(school_id),
  recipient         VARCHAR(60) NOT NULL,
  message           TEXT NOT NULL,
  channel           public.comm_channel NOT NULL DEFAULT 'sms',
  status            public.comm_status NOT NULL DEFAULT 'queued',
  sent_by_user_id   BIGINT NULL REFERENCES public.users(user_id),
  sent_at           TIMESTAMPTZ NULL,
  provider_response TEXT NULL,
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sms_school_status
  ON public.sms_logs (school_id, status);

CREATE INDEX IF NOT EXISTS idx_sms_deleted
  ON public.sms_logs (is_deleted);

