-- EduCore Postgres/Supabase schema (payments dependency)
-- Creates ONLY the `payments` table (depends on `schools`, `students`).
--
-- Important: backend code references `payments.invoice_id`, but your MySQL `schema.sql`
-- does not currently define it. We include it here (nullable) so the Postgres side matches
-- the backend queries. Confirm whether your live MySQL DB already has this column before
-- switching payment-related routes.

DO $$
BEGIN
  CREATE TYPE public.payment_status AS ENUM ('paid','pending','failed','reversed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.payments (
  payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id           BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id          BIGINT NOT NULL REFERENCES public.students(student_id),
  invoice_id          BIGINT NULL REFERENCES public.invoices(invoice_id),
  fee_structure_id    BIGINT NULL REFERENCES public.fee_structures(fee_structure_id),
  amount              NUMERIC(12,2) NOT NULL,
  fee_type            VARCHAR(60)  NOT NULL DEFAULT 'tuition',
  payment_method      VARCHAR(40)  NOT NULL DEFAULT 'cash',
  reference_number    VARCHAR(100) NULL,
  payment_date        DATE NOT NULL,
  status              public.payment_status NOT NULL DEFAULT 'paid',
  paid_by             VARCHAR(120) NULL,
  term                VARCHAR(40)  NOT NULL DEFAULT 'Term 2',
  received_by_user_id BIGINT NULL REFERENCES public.users(user_id),
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_school_student_date
  ON public.payments (school_id, student_id, payment_date);

CREATE INDEX IF NOT EXISTS idx_payments_school_status
  ON public.payments (school_id, status);

CREATE INDEX IF NOT EXISTS idx_payments_reference
  ON public.payments (reference_number);

CREATE INDEX IF NOT EXISTS idx_payments_invoice
  ON public.payments (invoice_id);

CREATE INDEX IF NOT EXISTS idx_payments_deleted
  ON public.payments (is_deleted);

