-- EduCore Postgres/Supabase schema
-- Creates ONLY the `teacher_classes` table (depends on `schools`, `teachers`, `classes`).

DO $$
BEGIN
  CREATE TYPE public.teacher_class_role AS ENUM ('class_teacher','subject_teacher');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.teacher_classes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id  BIGINT NOT NULL REFERENCES public.schools(school_id),
  teacher_id BIGINT NOT NULL REFERENCES public.teachers(teacher_id),
  class_id   BIGINT NOT NULL REFERENCES public.classes(class_id),
  role       public.teacher_class_role NOT NULL DEFAULT 'subject_teacher',
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_teacher_class_role
  ON public.teacher_classes (school_id, teacher_id, class_id, role);

CREATE INDEX IF NOT EXISTS idx_teacher_classes_deleted
  ON public.teacher_classes (is_deleted);

