import express from "express";
import cors from "cors";
import morgan from "morgan";
import { env } from "./config/env.js";
import healthRoutes        from "./routes/health.routes.js";
import authRoutes          from "./routes/auth.routes.js";
import studentsRoutes      from "./routes/students.routes.js";
import teachersRoutes      from "./routes/teachers.routes.js";
import attendanceRoutes    from "./routes/attendance.routes.js";
import gradesRoutes        from "./routes/grades.routes.js";
import paymentsRoutes      from "./routes/payments.routes.js";
import reportsRoutes       from "./routes/reports.routes.js";
import communicationRoutes from "./routes/communication.routes.js";
import integrationsRoutes  from "./routes/integrations.routes.js";
import disciplineRoutes    from "./routes/discipline.routes.js";
import transportRoutes     from "./routes/transport.routes.js";
import settingsRoutes      from "./routes/settings.routes.js";
import mpesaRoutes         from "./routes/mpesa.routes.js";
import paystackRoutes      from "./routes/paystack.routes.js";
import accountsRoutes      from "./routes/accounts.routes.js";
import timetableRoutes     from "./routes/timetable.routes.js";
import admissionsRoutes    from "./routes/admissions.routes.js";
import invoicesRoutes      from "./routes/invoices.routes.js";
import reportcardsRoutes   from "./routes/reportcards.routes.js";
import analyticsRoutes     from "./routes/analytics.routes.js";
import hrRoutes            from "./routes/hr.routes.js";
import libraryRoutes       from "./routes/library.routes.js";
import { errorHandler }    from "./middleware/error.js";

const app = express();

app.use("/api/paystack/webhook", express.raw({ type: "application/json" }));
app.use(cors({ origin: env.corsOrigin }));
app.use(express.json({ limit: "2mb" }));
app.use(morgan("dev"));

app.use("/api",               healthRoutes);
app.use("/api/auth",          authRoutes);
app.use("/api/students",      studentsRoutes);
app.use("/api/teachers",      teachersRoutes);
app.use("/api/attendance",    attendanceRoutes);
app.use("/api/grades",        gradesRoutes);
app.use("/api/payments",      paymentsRoutes);
app.use("/api/reports",       reportsRoutes);
app.use("/api/communication", communicationRoutes);
app.use("/api/integrations",  integrationsRoutes);
app.use("/api/discipline",    disciplineRoutes);
app.use("/api/transport",     transportRoutes);
app.use("/api/settings",      settingsRoutes);
app.use("/api/mpesa",         mpesaRoutes);
app.use("/api/paystack",      paystackRoutes);
app.use("/api/accounts",      accountsRoutes);
app.use("/api/timetable",     timetableRoutes);
app.use("/api/admissions",    admissionsRoutes);
app.use("/api/invoices",      invoicesRoutes);
app.use("/api/reportcards",   reportcardsRoutes);
app.use("/api/analytics",     analyticsRoutes);
app.use("/api/hr",            hrRoutes);
app.use("/api/library",       libraryRoutes);

app.use((req, res) => res.status(404).json({ message: "Not found" }));
app.use(errorHandler);

export default app;