-- Add columns for student promotion system

-- Add next_class_name to classes table
ALTER TABLE classes ADD COLUMN IF NOT EXISTS next_class_name VARCHAR(80) NULL;

-- Add class_order for proper ordering
ALTER TABLE classes ADD COLUMN IF NOT EXISTS class_order SMALLINT DEFAULT 0;

-- Create promotion_rules table if not exists
CREATE TABLE IF NOT EXISTS promotion_rules (
  rule_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id                  BIGINT NOT NULL REFERENCES schools(school_id),
  from_class_name            VARCHAR(80) NOT NULL,
  to_class_name              VARCHAR(80),
  minimum_overall_percentage NUMERIC(5,2) NULL,
  minimum_subject_percentage NUMERIC(5,2) NULL,
  maximum_failed_subjects    SMALLINT DEFAULT 0,
  auto_promote               BOOLEAN DEFAULT TRUE,
  requires_exam              BOOLEAN DEFAULT TRUE,
  is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_promotion_rules_school_from
  ON promotion_rules (school_id, from_class_name) WHERE NOT is_deleted AND is_active;

-- Create promotion_decisions table if not exists
CREATE TABLE IF NOT EXISTS promotion_decisions (
  decision_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id            BIGINT NOT NULL REFERENCES students(student_id),
  academic_year_id      BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  from_class_id         BIGINT NOT NULL REFERENCES classes(class_id),
  to_class_id           BIGINT REFERENCES classes(class_id),
  decision              VARCHAR(20) NOT NULL CHECK (decision IN ('promoted', 'retained', 'graduated', 'transferred')),
  decision_date         DATE NOT NULL,
  overall_percentage   NUMERIC(5,2) NULL,
  failed_subjects       TEXT[],
  special_consideration BOOLEAN DEFAULT FALSE,
  consideration_reason  TEXT,
  decided_by            BIGINT REFERENCES users(user_id),
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_promotion_decisions_student
  ON promotion_decisions (student_id) WHERE NOT is_deleted;