-- COMPLETE SAFE MIGRATION: Branch Support
-- NO DELETIONS - Only creates if missing, adds columns if missing
-- Run this in Supabase SQL Editor

-- Step 1: Create schools table ONLY if it doesn't exist (safe)
CREATE TABLE IF NOT EXISTS public.schools (
  school_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                VARCHAR(160) NOT NULL,
  code                VARCHAR(40)  NOT NULL UNIQUE,
  email               VARCHAR(160) NULL,
  phone               VARCHAR(40)  NULL,
  address             VARCHAR(255) NULL,
  county              VARCHAR(120) NULL,
  country             VARCHAR(120) NOT NULL DEFAULT 'Kenya',
  subscription_status VARCHAR(20)  NOT NULL DEFAULT 'trial',
  subscription_start  DATE NULL,
  subscription_end    DATE NULL,
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Step 2: Create users table ONLY if it doesn't exist (needed for branch_manager_id)
CREATE TABLE IF NOT EXISTS public.users (
  user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id      BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id     BIGINT NULL,
  full_name      VARCHAR(160) NOT NULL,
  email          VARCHAR(160) NOT NULL,
  phone          VARCHAR(40)  NULL,
  password_hash  VARCHAR(255) NOT NULL,
  role           VARCHAR(20)  NOT NULL,
  status         VARCHAR(20)  NOT NULL DEFAULT 'active',
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Step 3: Add branch columns ONLY if they don't exist (100% safe)
DO $$
BEGIN
  -- parent_school_id
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='parent_school_id') THEN
    ALTER TABLE public.schools ADD COLUMN parent_school_id BIGINT NULL 
    REFERENCES public.schools(school_id);
  END IF;

  -- is_branch
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='is_branch') THEN
    ALTER TABLE public.schools ADD COLUMN is_branch BOOLEAN NOT NULL DEFAULT FALSE;
  END IF;

  -- branch_code
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='branch_code') THEN
    ALTER TABLE public.schools ADD COLUMN branch_code VARCHAR(40) NULL;
  END IF;

  -- branch_address
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='branch_address') THEN
    ALTER TABLE public.schools ADD COLUMN branch_address VARCHAR(255) NULL;
  END IF;

  -- branch_phone
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='branch_phone') THEN
    ALTER TABLE public.schools ADD COLUMN branch_phone VARCHAR(40) NULL;
  END IF;

  -- branch_manager_id
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='schools' AND column_name='branch_manager_id') THEN
    ALTER TABLE public.schools ADD COLUMN branch_manager_id BIGINT NULL 
    REFERENCES public.users(user_id);
  END IF;
END $$;

-- Step 4: Add indexes ONLY if they don't exist
CREATE INDEX IF NOT EXISTS idx_schools_parent ON public.schools (parent_school_id);
CREATE INDEX IF NOT EXISTS idx_schools_is_branch ON public.schools (is_branch) WHERE is_branch = TRUE;

-- Step 5: Add unique constraint ONLY if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'uq_schools_parent_branch'
  ) THEN
    ALTER TABLE public.schools 
    ADD CONSTRAINT uq_schools_parent_branch 
    UNIQUE (parent_school_id, branch_code);
  END IF;
END $$;

-- Done! All changes are additive - nothing was deleted.
-- Existing data is preserved.
