-- =====================================================
-- PARALLEL ARCHITECTURE LAYER FOR EDUCORE
-- Safe, Additive Migration - No Existing Data Modified
-- =====================================================

-- =====================================================
-- PHASE 1: NEW TABLES FOR ACADEMIC CALENDAR MANAGEMENT
-- =====================================================

-- Academic Years Table (Parallel to school_settings.academic_year)
CREATE TABLE IF NOT EXISTS academic_years (
  academic_year_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          BIGINT NOT NULL REFERENCES schools(school_id),
  year_label         VARCHAR(20) NOT NULL, -- "2024-2025" or "2026"
  start_date         DATE NOT NULL,
  end_date           DATE NOT NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'active'
                     CHECK (status IN ('upcoming', 'active', 'completed')),
  legacy_year_value SMALLINT NULL, -- Maps to classes.academic_year
  is_current         BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add unique constraint and indexes
CREATE UNIQUE INDEX IF NOT EXISTS uq_academic_years_school_label
  ON academic_years (school_id, year_label) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_academic_years_school_status
  ON academic_years (school_id, status) WHERE NOT is_deleted;

-- Terms Table (Parallel to school_settings.current_term and various term fields)
CREATE TABLE IF NOT EXISTS terms (
  term_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          BIGINT NOT NULL REFERENCES schools(school_id),
  academic_year_id   BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  term_name          VARCHAR(40) NOT NULL, -- "Term 1", "Term 2", "Term 3"
  term_order         SMALLINT NOT NULL, -- 1, 2, 3 for sequencing
  start_date         DATE NOT NULL,
  end_date           DATE NOT NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'upcoming'
                     CHECK (status IN ('upcoming', 'active', 'completed')),
  legacy_term_value  VARCHAR(40) NULL, -- Maps to invoices.term, payments.term
  is_current         BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add unique constraint and indexes
CREATE UNIQUE INDEX IF NOT EXISTS uq_terms_school_year_name
  ON terms (school_id, academic_year_id, term_name) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_terms_school_status
  ON terms (school_id, status) WHERE NOT is_deleted;

-- =====================================================
-- PHASE 2: STUDENT ENROLLMENT HISTORY TRACKING
-- =====================================================

-- Student Enrollments Table (Tracks historical enrollments, parallel to students.class_id)
CREATE TABLE IF NOT EXISTS student_enrollments (
  enrollment_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id            BIGINT NOT NULL REFERENCES students(student_id),
  class_id              BIGINT NOT NULL REFERENCES classes(class_id),
  academic_year_id      BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  term_id               BIGINT REFERENCES terms(term_id),
  enrollment_date       DATE NOT NULL,
  status                VARCHAR(20) NOT NULL DEFAULT 'active'
                         CHECK (status IN ('active', 'transferred', 'graduated', 'withdrawn')),
  enrollment_type       VARCHAR(20) NOT NULL DEFAULT 'regular'
                         CHECK (enrollment_type IN ('regular', 'promotion', 'demotion', 'transfer', 'repeat')),
  previous_class_id     BIGINT REFERENCES classes(class_id),
  next_class_id         BIGINT REFERENCES classes(class_id),
  performance_notes     TEXT,
  created_by            BIGINT REFERENCES users(user_id),
  is_current            BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_student_enrollments_student
  ON student_enrollments (student_id) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_student_enrollments_class
  ON student_enrollments (class_id) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_student_enrollments_school_year
  ON student_enrollments (student_id, academic_year_id) WHERE NOT is_deleted;

-- =====================================================
-- PHASE 3: FEE BALANCE TRACKING & CARRY-FORWARD
-- =====================================================

-- Fee Balance Ledger (Tracks balance changes over time, parallel to invoices.balance)
CREATE TABLE IF NOT EXISTS fee_balance_ledger (
  ledger_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          BIGINT NOT NULL REFERENCES schools(school_id),
  student_id         BIGINT NOT NULL REFERENCES students(student_id),
  academic_year_id   BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  term_id            BIGINT REFERENCES terms(term_id),
  transaction_type   VARCHAR(20) NOT NULL
                      CHECK (transaction_type IN ('charge', 'payment', 'carry_forward', 'waiver', 'adjustment')),
  transaction_date   DATE NOT NULL,
  amount             NUMERIC(12,2) NOT NULL, -- Positive for charges, negative for payments
  balance_before     NUMERIC(12,2) NOT NULL,
  balance_after      NUMERIC(12,2) NOT NULL,
  reference_type     VARCHAR(20) NOT NULL
                      CHECK (reference_type IN ('invoice', 'payment', 'manual')),
  reference_id       BIGINT NOT NULL, -- Links to invoices.id or payments.id
  description        TEXT,
  created_by         BIGINT REFERENCES users(user_id),
  is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_fee_ledger_student
  ON fee_balance_ledger (student_id, transaction_date) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_fee_ledger_school_year_term
  ON fee_balance_ledger (school_id, academic_year_id, term_id) WHERE NOT is_deleted;

-- Fee Carry-Forward Records (Tracks balances carried between terms)
CREATE TABLE IF NOT EXISTS fee_carry_forwards (
  carry_forward_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id            BIGINT NOT NULL REFERENCES schools(school_id),
  student_id           BIGINT NOT NULL REFERENCES students(student_id),
  from_term_id         BIGINT NOT NULL REFERENCES terms(term_id),
  to_term_id           BIGINT NOT NULL REFERENCES terms(term_id),
  amount_carried       NUMERIC(12,2) NOT NULL,
  carry_forward_date   DATE NOT NULL,
  status               VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'completed', 'cancelled')),
  processed_by         BIGINT REFERENCES users(user_id),
  notes                TEXT,
  is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_carry_forwards_student
  ON fee_carry_forwards (student_id) WHERE NOT is_deleted;

-- =====================================================
-- PHASE 4: PROMOTION RULES & DECISIONS
-- =====================================================

-- Promotion Rules Configuration (School-specific promotion criteria)
CREATE TABLE IF NOT EXISTS promotion_rules (
  rule_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id                  BIGINT NOT NULL REFERENCES schools(school_id),
  from_class_name            VARCHAR(80) NOT NULL, -- Maps to classes.class_name
  to_class_name              VARCHAR(80), -- NULL for graduation
  minimum_overall_percentage NUMERIC(5,2) NULL,
  minimum_subject_percentage NUMERIC(5,2) NULL,
  maximum_failed_subjects    SMALLINT DEFAULT 0,
  auto_promote               BOOLEAN DEFAULT TRUE,
  requires_exam              BOOLEAN DEFAULT TRUE,
  is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add unique constraint
CREATE UNIQUE INDEX IF NOT EXISTS uq_promotion_rules_school_from
  ON promotion_rules (school_id, from_class_name) WHERE NOT is_deleted AND is_active;

-- Promotion Decisions (Records actual promotion outcomes)
CREATE TABLE IF NOT EXISTS promotion_decisions (
  decision_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id            BIGINT NOT NULL REFERENCES students(student_id),
  academic_year_id      BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  from_class_id         BIGINT NOT NULL REFERENCES classes(class_id),
  to_class_id           BIGINT REFERENCES classes(class_id), -- NULL for graduation
  decision              VARCHAR(20) NOT NULL
                         CHECK (decision IN ('promoted', 'retained', 'graduated', 'transferred')),
  decision_date         DATE NOT NULL,
  overall_percentage    NUMERIC(5,2) NULL,
  failed_subjects       TEXT[] NULL, -- Array of subject names
  special_consideration BOOLEAN DEFAULT FALSE,
  consideration_reason  TEXT,
  decided_by            BIGINT REFERENCES users(user_id),
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_promotion_decisions_student
  ON promotion_decisions (student_id) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_promotion_decisions_year
  ON promotion_decisions (academic_year_id) WHERE NOT is_deleted;

-- =====================================================
-- PHASE 5: TERM TRANSITION AUDIT TRAIL
-- =====================================================

-- Term Transitions (Audit log for term closing events)
CREATE TABLE IF NOT EXISTS term_transitions (
  transition_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id            BIGINT NOT NULL REFERENCES schools(school_id),
  term_id              BIGINT NOT NULL REFERENCES terms(term_id),
  transition_type      VARCHAR(20) NOT NULL
                        CHECK (transition_type IN ('close_term', 'open_term', 'rollover')),
  transition_date      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  initiated_by         BIGINT REFERENCES users(user_id),
  status               VARCHAR(20) NOT NULL DEFAULT 'completed'
                        CHECK (status IN ('pending', 'completed', 'failed')),
  summary_stats        JSONB NULL, -- Store counts, totals, etc.
  notes                TEXT,
  is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_term_transitions_school_term
  ON term_transitions (school_id, term_id) WHERE NOT is_deleted;

-- =====================================================
-- PHASE 6: MAPPING TABLES FOR LEGACY DATA INTEGRATION
-- =====================================================

-- Class to Academic Year Mapping (Links existing classes to new academic_years)
CREATE TABLE IF NOT EXISTS class_academic_year_mapping (
  mapping_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id           BIGINT NOT NULL REFERENCES classes(class_id),
  academic_year_id   BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
  is_primary         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add unique constraint
CREATE UNIQUE INDEX IF NOT EXISTS uq_class_year_mapping
  ON class_academic_year_mapping (class_id) WHERE is_primary;

-- Invoice to Term Mapping (Links existing invoices to new terms)
CREATE TABLE IF NOT EXISTS invoice_term_mapping (
  mapping_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id   BIGINT NOT NULL REFERENCES invoices(invoice_id),
  term_id      BIGINT NOT NULL REFERENCES terms(term_id),
  is_primary   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add unique constraint
CREATE UNIQUE INDEX IF NOT EXISTS uq_invoice_term_mapping
  ON invoice_term_mapping (invoice_id) WHERE is_primary;

-- =====================================================
-- PHASE 7: DATA INTEGRITY CONSTRAINTS
-- =====================================================

-- Ensure only one current academic year per school
CREATE UNIQUE INDEX IF NOT EXISTS uq_academic_years_current
  ON academic_years (school_id) WHERE is_current = TRUE AND NOT is_deleted;

-- Ensure only one current term per school
CREATE UNIQUE INDEX IF NOT EXISTS uq_terms_current
  ON terms (school_id) WHERE is_current = TRUE AND NOT is_deleted;

-- Ensure only one current enrollment per student
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_enrollments_current
  ON student_enrollments (student_id) WHERE is_current = TRUE AND NOT is_deleted;

-- =====================================================
-- PHASE 8: ROLLBACK SUPPORT TABLES
-- =====================================================

-- Migration Checkpoints (Track migration progress for rollback)
CREATE TABLE IF NOT EXISTS migration_checkpoints (
  checkpoint_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_phase   VARCHAR(50) NOT NULL,
  school_id         BIGINT REFERENCES schools(school_id),
  checkpoint_data   JSONB NULL,
  status            VARCHAR(20) NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'completed', 'failed')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add index
CREATE INDEX IF NOT EXISTS idx_migration_checkpoints_phase
  ON migration_checkpoints (migration_phase, status);