-- EduCore Postgres/Supabase schema (next dependency for grades/timetable)
-- Creates ONLY the `teachers` table (depends on `schools`, `users`).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - ENUM -> Postgres enum types
-- - TINYINT(1) -> boolean

DO $$
BEGIN
  CREATE TYPE public.teacher_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.teachers (
  teacher_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     BIGINT NOT NULL REFERENCES public.schools(school_id),
  user_id       BIGINT NULL REFERENCES public.users(user_id),
  staff_number  VARCHAR(60)  NULL,
  national_id   VARCHAR(40)  NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(160) NULL,
  phone         VARCHAR(40)  NULL,
  hire_date     DATE NULL,
  department    VARCHAR(120) NULL,
  qualification VARCHAR(120) NULL,
  status        public.teacher_status NOT NULL DEFAULT 'active',
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_teachers_school_staff
  ON public.teachers (school_id, staff_number);

CREATE INDEX IF NOT EXISTS idx_teachers_school_status
  ON public.teachers (school_id, status);

CREATE INDEX IF NOT EXISTS idx_teachers_deleted
  ON public.teachers (is_deleted);

