-- EduCore Postgres/Supabase schema
-- Creates ONLY the `student_guardians` table (depends on `schools`, `students`, `guardians`).

CREATE TABLE IF NOT EXISTS public.student_guardians (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id                BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id               BIGINT NOT NULL REFERENCES public.students(student_id),
  guardian_id              BIGINT NOT NULL REFERENCES public.guardians(guardian_id),
  can_pickup               BOOLEAN NOT NULL DEFAULT TRUE,
  financial_responsibility BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted               BOOLEAN NOT NULL DEFAULT FALSE,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_guardian
  ON public.student_guardians (school_id, student_id, guardian_id);

CREATE INDEX IF NOT EXISTS idx_student_guardians_deleted
  ON public.student_guardians (is_deleted);

