-- EduCore Postgres/Supabase schema
-- Creates ONLY the `hr_leave` table (depends on `schools`, `hr_staff`).

DO $$
BEGIN
  CREATE TYPE public.hr_leave_status AS ENUM ('pending','approved','rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.hr_leave (
  leave_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id  BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id   BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  leave_type VARCHAR(60) NOT NULL DEFAULT 'Annual',
  from_date  DATE NOT NULL,
  to_date    DATE NOT NULL,
  reason     TEXT NULL,
  status     public.hr_leave_status NOT NULL DEFAULT 'pending',
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

