-- EduCore Postgres/Supabase schema (grades dependency)
-- Creates ONLY the `class_subjects` table (depends on `schools`, `classes`, `subjects`, `teachers`).

CREATE TABLE IF NOT EXISTS public.class_subjects (
  class_subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  class_id         BIGINT NOT NULL REFERENCES public.classes(class_id),
  subject_id       BIGINT NOT NULL REFERENCES public.subjects(subject_id),
  teacher_id       BIGINT NULL REFERENCES public.teachers(teacher_id),
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_class_subject_teacher
  ON public.class_subjects (school_id, class_id, subject_id, teacher_id);

CREATE INDEX IF NOT EXISTS idx_class_subjects_deleted
  ON public.class_subjects (is_deleted);

