-- EduCore Postgres/Supabase schema
-- Creates ONLY the `announcements` table (depends on `schools`, `users`).

DO $$
BEGIN
  CREATE TYPE public.announcement_type AS ENUM ('general','academic','event','emergency');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.announcement_status AS ENUM ('draft','published','archived');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.announcements (
  announcement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         BIGINT NOT NULL REFERENCES public.schools(school_id),
  title             VARCHAR(200) NOT NULL,
  message           TEXT NOT NULL,
  type              public.announcement_type NOT NULL DEFAULT 'general',
  status            public.announcement_status NOT NULL DEFAULT 'draft',
  priority          VARCHAR(20) NOT NULL DEFAULT 'normal',
  target_audience   VARCHAR(50) NOT NULL DEFAULT 'all',
  pinned            BOOLEAN NOT NULL DEFAULT FALSE,
  author_user_id    BIGINT NULL REFERENCES public.users(user_id),
  publish_date      TIMESTAMPTZ NULL,
  expiry_date       TIMESTAMPTZ NULL,
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_announcements_school_status 
  ON public.announcements (school_id, status);

CREATE INDEX IF NOT EXISTS idx_announcements_school_published 
  ON public.announcements (school_id, publish_date);

CREATE INDEX IF NOT EXISTS idx_announcements_target_audience 
  ON public.announcements (target_audience);

CREATE INDEX IF NOT EXISTS idx_announcements_deleted 
  ON public.announcements (is_deleted);
