-- EduCore Postgres/Supabase schema
-- Creates ONLY the `hr_attendance` table (depends on `schools`, `hr_staff`).

DO $$
BEGIN
  CREATE TYPE public.hr_attendance_status AS ENUM ('present','absent','late','half-day','on-leave');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.hr_attendance (
  hr_attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id         BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  attendance_date  DATE NOT NULL,
  check_in         TIME NULL,
  check_out        TIME NULL,
  status           public.hr_attendance_status NOT NULL DEFAULT 'present',
  notes            TEXT NULL,
  marked_by        BIGINT NULL,
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_att
  ON public.hr_attendance (school_id, staff_id, attendance_date);

