-- EduCore Postgres/Supabase schema (payments dependency)
-- Creates ONLY the `invoices` table (depends on `schools`, `students`).

DO $$
BEGIN
  CREATE TYPE public.invoice_status AS ENUM ('unpaid','partial','paid');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.invoices (
  invoice_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id      BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id     BIGINT NOT NULL REFERENCES public.students(student_id),
  invoice_number VARCHAR(100) NULL,
  term           VARCHAR(40)  NOT NULL DEFAULT 'Term 2',
  academic_year  VARCHAR(20)  NOT NULL DEFAULT '2026',
  tuition        NUMERIC(12,2) NOT NULL DEFAULT 0,
  activity       NUMERIC(12,2) NOT NULL DEFAULT 0,
  transport      NUMERIC(12,2) NOT NULL DEFAULT 0,
  misc           NUMERIC(12,2) NOT NULL DEFAULT 0,
  total          NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount_paid    NUMERIC(12,2) NOT NULL DEFAULT 0,
  balance        NUMERIC(12,2) NOT NULL DEFAULT 0,
  due_date       DATE NULL,
  status         public.invoice_status NOT NULL DEFAULT 'unpaid',
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoices_school_student
  ON public.invoices (school_id, student_id);

CREATE INDEX IF NOT EXISTS idx_invoices_deleted
  ON public.invoices (is_deleted);

