-- EduCore Postgres/Supabase schema
-- Creates ONLY the `borrow_records` table (depends on `schools`, `books`).

DO $$
BEGIN
  CREATE TYPE public.borrower_type AS ENUM ('student','staff');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.borrow_status AS ENUM ('borrowed','returned','overdue');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.borrow_records (
  borrow_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id           BIGINT NOT NULL REFERENCES public.schools(school_id),
  book_id             BIGINT NOT NULL REFERENCES public.books(book_id),
  borrower_id         BIGINT NOT NULL,
  borrower_type       public.borrower_type NOT NULL DEFAULT 'student',
  borrow_date         DATE NOT NULL,
  due_date            DATE NOT NULL,
  return_date         DATE NULL,
  status              public.borrow_status NOT NULL DEFAULT 'borrowed',
  notes               TEXT NULL,
  issued_by_user_id   BIGINT NULL,
  returned_to_user_id BIGINT NULL,
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_borrow_school_status
  ON public.borrow_records (school_id, status);

CREATE INDEX IF NOT EXISTS idx_borrow_deleted
  ON public.borrow_records (is_deleted);

