-- EduCore Postgres/Supabase schema
-- Creates ONLY the `hr_payslips` table (depends on `schools`, `hr_staff`).

DO $$
BEGIN
  CREATE TYPE public.hr_payslip_status AS ENUM ('draft','approved','paid');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.hr_payslips (
  payslip_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id     BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  month        SMALLINT NOT NULL,
  year         SMALLINT NOT NULL,
  basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
  allowances   NUMERIC(12,2) NOT NULL DEFAULT 0,
  deductions   NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_pay      NUMERIC(12,2) NOT NULL DEFAULT 0,
  paye         NUMERIC(12,2) NOT NULL DEFAULT 0,
  nhif         NUMERIC(12,2) NOT NULL DEFAULT 0,
  nssf         NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes        TEXT NULL,
  status       public.hr_payslip_status NOT NULL DEFAULT 'draft',
  paid_date    DATE NULL,
  generated_by BIGINT NULL,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payslip
  ON public.hr_payslips (school_id, staff_id, month, year);

