-- EduCore Postgres/Supabase schema (payments dependency)
-- Creates ONLY the `fee_structures` table (depends on `schools`).

CREATE TABLE IF NOT EXISTS public.fee_structures (
  fee_structure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  class_name       VARCHAR(80)  NOT NULL,
  term             VARCHAR(40)  NOT NULL DEFAULT 'Term 2',
  tuition          NUMERIC(12,2) NOT NULL DEFAULT 0,
  activity         NUMERIC(12,2) NOT NULL DEFAULT 0,
  misc             NUMERIC(12,2) NOT NULL DEFAULT 0,
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fee_structure_class_term
  ON public.fee_structures (school_id, class_name, term);

CREATE INDEX IF NOT EXISTS idx_fee_structures_deleted
  ON public.fee_structures (is_deleted);

