-- EduCore Postgres/Supabase schema (Step 2)
-- This file creates ONLY the `students` table (depends on `schools`, `classes`).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - ENUM -> Postgres enum types
-- - TINYINT(1) -> boolean
-- - Postgres string comparisons are case-sensitive; use ILIKE in queries where needed.

DO $$
BEGIN
  CREATE TYPE public.gender_type AS ENUM ('male','female','other');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.student_status AS ENUM ('active','inactive','graduated','transferred');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.students (
  student_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  class_id         BIGINT NULL REFERENCES public.classes(class_id),
  class_name       VARCHAR(80)  NULL,
  admission_number VARCHAR(60)  NOT NULL,
  first_name       VARCHAR(100) NOT NULL,
  last_name        VARCHAR(100) NOT NULL,
  gender           public.gender_type NOT NULL,
  date_of_birth    DATE NULL,
  phone            VARCHAR(40)  NULL,
  email            VARCHAR(160) NULL,
  address          VARCHAR(255) NULL,
  parent_name      VARCHAR(160) NULL,
  parent_phone     VARCHAR(40)  NULL,
  admission_date   DATE NULL,
  photo_url        TEXT NULL,
  status           public.student_status NOT NULL DEFAULT 'active',
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_students_school_adm
  ON public.students (school_id, admission_number);

CREATE INDEX IF NOT EXISTS idx_students_school_class
  ON public.students (school_id, class_id);

CREATE INDEX IF NOT EXISTS idx_students_school_status
  ON public.students (school_id, status);

CREATE INDEX IF NOT EXISTS idx_students_parent_phone
  ON public.students (school_id, parent_phone);

CREATE INDEX IF NOT EXISTS idx_students_deleted
  ON public.students (is_deleted);

