-- EduCore Postgres/Supabase schema
-- Creates ONLY the `timetable_entries` table (depends on `schools`, `classes`, `teachers`).

DO $$
BEGIN
  CREATE TYPE public.day_of_week AS ENUM ('Mon','Tue','Wed','Thu','Fri','Sat','Sun');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.timetable_entries (
  timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    BIGINT NOT NULL REFERENCES public.schools(school_id),
  class_id     BIGINT NOT NULL REFERENCES public.classes(class_id),
  subject_name VARCHAR(120) NOT NULL,
  teacher_id   BIGINT NULL REFERENCES public.teachers(teacher_id),
  day_of_week  public.day_of_week NOT NULL,
  start_time   TIME NOT NULL,
  end_time     TIME NOT NULL,
  room         VARCHAR(40) NULL,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_timetable_school_class_day
  ON public.timetable_entries (school_id, class_id, day_of_week);

CREATE INDEX IF NOT EXISTS idx_timetable_deleted
  ON public.timetable_entries (is_deleted);

