-- EduCore Postgres/Supabase schema (Step 2)
-- This file creates ONLY the `classes` table (depends on `schools`).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - ENUM -> Postgres enum types
-- - TINYINT(1) -> boolean
-- - FK to `teachers` is added later (teachers table not created yet).

DO $$
BEGIN
  CREATE TYPE public.class_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.classes (
  class_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  class_name       VARCHAR(80) NOT NULL,
  section          VARCHAR(20) NULL,
  class_teacher_id BIGINT NULL,
  academic_year    SMALLINT NOT NULL,
  status           public.class_status NOT NULL DEFAULT 'active',
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_classes_school_name_section_year
  ON public.classes (school_id, class_name, section, academic_year);

CREATE INDEX IF NOT EXISTS idx_classes_school_status ON public.classes (school_id, status);
CREATE INDEX IF NOT EXISTS idx_classes_deleted       ON public.classes (is_deleted);

