-- EduCore Postgres/Supabase schema (next table for grades)
-- Creates ONLY the `subjects` table (depends on `schools`).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - ENUM -> Postgres enum types
-- - TINYINT(1) -> boolean

DO $$
BEGIN
  CREATE TYPE public.subject_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.subjects (
  subject_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    BIGINT NOT NULL REFERENCES public.schools(school_id),
  subject_name VARCHAR(120) NOT NULL,
  code         VARCHAR(30)  NOT NULL,
  status       public.subject_status NOT NULL DEFAULT 'active',
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_subject_school_code
  ON public.subjects (school_id, code);

CREATE INDEX IF NOT EXISTS idx_subjects_school_status
  ON public.subjects (school_id, status);

CREATE INDEX IF NOT EXISTS idx_subjects_deleted
  ON public.subjects (is_deleted);

