-- EduCore Postgres/Supabase schema
-- Creates ONLY the `student_transport` table (depends on `schools`, `students`, `transport_routes`).

DO $$
BEGIN
  CREATE TYPE public.student_transport_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.student_transport (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id   BIGINT NOT NULL REFERENCES public.students(student_id),
  transport_id BIGINT NOT NULL REFERENCES public.transport_routes(transport_id),
  start_date   DATE NOT NULL,
  end_date     DATE NULL,
  status       public.student_transport_status NOT NULL DEFAULT 'active',
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_transport_active
  ON public.student_transport (school_id, student_id, transport_id, start_date);

CREATE INDEX IF NOT EXISTS idx_student_transport_deleted
  ON public.student_transport (is_deleted);

