-- EduCore Postgres/Supabase schema
-- Creates ONLY the `notifications` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.notification_type AS ENUM ('info','success','warning','error');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id       BIGINT NOT NULL REFERENCES public.schools(school_id),
  user_id         BIGINT NULL,
  title           VARCHAR(200) NOT NULL,
  message         TEXT NOT NULL,
  type            public.notification_type NOT NULL DEFAULT 'info',
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  link            VARCHAR(255) NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

