-- EduCore Postgres/Supabase schema
-- Creates ONLY the `activity_logs` table (used by backend activity logger).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - DATETIME -> TIMESTAMPTZ

CREATE TABLE IF NOT EXISTS public.activity_logs (
  log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   BIGINT NOT NULL,
  user_id     BIGINT NULL,          -- NULL for system actions
  role        VARCHAR(30) NULL,
  action      VARCHAR(80) NOT NULL, -- e.g. "payment.create"
  entity      VARCHAR(60) NULL,     -- e.g. "payment", "student"
  entity_id   BIGINT NULL,          -- e.g. payment_id
  description VARCHAR(255) NULL,    -- human-readable summary
  ip_address  VARCHAR(45) NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_school_created
  ON public.activity_logs (school_id, created_at);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user
  ON public.activity_logs (user_id);

CREATE INDEX IF NOT EXISTS idx_activity_logs_action
  ON public.activity_logs (action);

