-- EduCore Postgres/Supabase schema
-- Creates ONLY the `hr_staff` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.hr_contract_type AS ENUM ('Permanent','Contract','Part-time','Volunteer');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.hr_staff_status AS ENUM ('active','inactive','on-leave');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.hr_staff (
  staff_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     BIGINT NOT NULL REFERENCES public.schools(school_id),
  full_name     VARCHAR(200) NOT NULL,
  email         VARCHAR(160) NULL,
  phone         VARCHAR(40)  NULL,
  national_id   VARCHAR(40)  NULL,
  department    VARCHAR(100) NOT NULL DEFAULT 'Academic',
  job_title     VARCHAR(100) NOT NULL,
  contract_type public.hr_contract_type NOT NULL DEFAULT 'Permanent',
  start_date    DATE NULL,
  salary        NUMERIC(12,2) NOT NULL DEFAULT 0,
  status        public.hr_staff_status NOT NULL DEFAULT 'active',
  notes         TEXT NULL,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

