-- EduCore Postgres/Supabase schema
-- Creates ONLY the `books` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.book_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.books (
  book_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          BIGINT NOT NULL REFERENCES public.schools(school_id),
  title              VARCHAR(255) NOT NULL,
  author             VARCHAR(160) NULL,
  category           VARCHAR(100) NULL,
  isbn               VARCHAR(50)  NULL,
  quantity_total     INTEGER NOT NULL DEFAULT 1,
  quantity_available INTEGER NOT NULL DEFAULT 1,
  status             public.book_status NOT NULL DEFAULT 'active',
  is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_books_school_title
  ON public.books (school_id, title);

CREATE INDEX IF NOT EXISTS idx_books_deleted
  ON public.books (is_deleted);

