-- EduCore Postgres/Supabase schema
-- Creates ONLY the `discipline_records` table (depends on `schools`, `students`, `teachers`).

DO $$
BEGIN
  CREATE TYPE public.discipline_status AS ENUM ('open','closed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.discipline_records (
  discipline_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id       BIGINT NOT NULL REFERENCES public.students(student_id),
  teacher_id       BIGINT NULL REFERENCES public.teachers(teacher_id),
  incident_type    VARCHAR(120) NOT NULL,
  incident_details TEXT NULL,
  action_taken     TEXT NULL,
  incident_date    DATE NOT NULL,
  status           public.discipline_status NOT NULL DEFAULT 'open',
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discipline_school_student
  ON public.discipline_records (school_id, student_id);

CREATE INDEX IF NOT EXISTS idx_discipline_date
  ON public.discipline_records (incident_date);

CREATE INDEX IF NOT EXISTS idx_discipline_deleted
  ON public.discipline_records (is_deleted);

