-- EduCore Postgres/Supabase schema
-- Creates ONLY the `transport_routes` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.transport_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.transport_routes (
  transport_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id      BIGINT NOT NULL REFERENCES public.schools(school_id),
  route_name     VARCHAR(120) NOT NULL,
  driver_name    VARCHAR(120) NULL,
  driver_phone   VARCHAR(40)  NULL,
  vehicle_number VARCHAR(40)  NULL,
  fee            NUMERIC(12,2) NOT NULL DEFAULT 0,
  status         public.transport_status NOT NULL DEFAULT 'active',
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_transport_route_name
  ON public.transport_routes (school_id, route_name);

CREATE INDEX IF NOT EXISTS idx_transport_deleted
  ON public.transport_routes (is_deleted);

