-- EduCore Security Logs table for audit trail and threat detection
-- This table stores security events for monitoring and compliance

CREATE TABLE IF NOT EXISTS public.security_logs (
  log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NULL,
  user_id          BIGINT NULL,
  role             VARCHAR(50) NULL,
  event_type       VARCHAR(100) NOT NULL,
  severity         VARCHAR(20) NOT NULL DEFAULT 'medium',
  description      TEXT NOT NULL,
  ip_address       VARCHAR(45) NULL,
  user_agent       TEXT NULL,
  details          JSON NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance and querying
CREATE INDEX IF NOT EXISTS idx_security_logs_school_event ON public.security_logs (school_id, event_type);
CREATE INDEX IF NOT EXISTS idx_security_logs_severity ON public.security_logs (severity);
CREATE INDEX IF NOT EXISTS idx_security_logs_created_at ON public.security_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_security_logs_ip_address ON public.security_logs (ip_address);

-- RLS policies for security logs
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;

-- Users can view security logs from their school only
CREATE POLICY "Users can view security logs from their school only" ON public.security_logs
  FOR SELECT
  USING (school_id = (auth.jwt() ->> 'school_id')::bigint);

-- System can insert security logs
CREATE POLICY "System can insert security logs" ON public.security_logs
  FOR INSERT
  WITH CHECK (true);

-- No updates or deletes for security logs (immutable audit trail)
CREATE POLICY "No updates to security logs" ON public.security_logs
  FOR UPDATE
  USING (false);

CREATE POLICY "No deletes to security logs" ON public.security_logs
  FOR DELETE
  USING (false);
