-- EduCore Postgres/Supabase schema (grades dependency)
-- Creates ONLY the `exams` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.exam_term AS ENUM ('Term 1','Term 2','Term 3');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.exam_status AS ENUM ('draft','published');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.exams (
  exam_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     BIGINT NOT NULL REFERENCES public.schools(school_id),
  exam_name     VARCHAR(120) NOT NULL,
  term          public.exam_term NOT NULL,
  academic_year SMALLINT NOT NULL,
  start_date    DATE NULL,
  end_date      DATE NULL,
  status        public.exam_status NOT NULL DEFAULT 'draft',
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_exams_school_term_year
  ON public.exams (school_id, term, academic_year);

CREATE INDEX IF NOT EXISTS idx_exams_deleted
  ON public.exams (is_deleted);

