-- EduCore Postgres/Supabase schema
-- Creates ONLY the `admissions` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.admission_status AS ENUM ('pending','reviewing','accepted','rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Reuse gender_type if it already exists (created by students schema); create if not.
DO $$
BEGIN
  CREATE TYPE public.gender_type AS ENUM ('male','female','other');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.admissions (
  admission_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id       BIGINT NOT NULL REFERENCES public.schools(school_id),
  full_name       VARCHAR(200) NOT NULL,
  date_of_birth   DATE NULL,
  gender          public.gender_type NULL,
  applying_class  VARCHAR(60)  NULL,
  academic_year   VARCHAR(20)  NOT NULL DEFAULT '2026',
  parent_name     VARCHAR(200) NULL,
  parent_phone    VARCHAR(40)  NULL,
  parent_email    VARCHAR(160) NULL,
  address         VARCHAR(255) NULL,
  previous_school VARCHAR(200) NULL,
  status          public.admission_status NOT NULL DEFAULT 'pending',
  notes           TEXT NULL,
  admission_fee   NUMERIC(12,2) NOT NULL DEFAULT 0,
  fee_paid        BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

