-- EduCore Payment Configuration Table
-- Multi-tenant payment provider configurations per school

CREATE TABLE IF NOT EXISTS public.payment_configs (
  config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL REFERENCES public.schools(school_id) ON DELETE CASCADE,
  
  -- M-Pesa Configuration
  mpesa_till_number VARCHAR(20) NULL,
  mpesa_paybill VARCHAR(20) NULL,
  mpesa_shortcode VARCHAR(20) NULL,
  mpesa_consumer_key TEXT NULL,
  mpesa_consumer_secret TEXT NULL,
  mpesa_passkey TEXT NULL,
  mpesa_environment VARCHAR(20) NOT NULL DEFAULT 'sandbox', -- sandbox or production
  mpesa_base_url VARCHAR(255) NULL,
  mpesa_callback_base_url VARCHAR(255) NULL,
  
  -- Paystack Configuration
  paystack_public_key TEXT NULL,
  paystack_secret_key TEXT NULL,
  paystack_environment VARCHAR(20) NOT NULL DEFAULT 'test', -- test or live
  paystack_callback_url VARCHAR(255) NULL,
  
  -- Bank Configuration
  bank_account_number VARCHAR(50) NULL,
  bank_name VARCHAR(100) NULL,
  bank_branch VARCHAR(100) NULL,
  account_name VARCHAR(200) NULL,
  
  -- SMS Configuration (for receipts)
  sms_enabled BOOLEAN NOT NULL DEFAULT false,
  sms_sender_id VARCHAR(20) NULL,
  
  -- Metadata
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  
  -- Note: Partial unique constraint implemented as unique index below
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_payment_configs_school_id ON public.payment_configs(school_id);
CREATE INDEX IF NOT EXISTS idx_payment_configs_active ON public.payment_configs(is_active, is_deleted);

-- Partial unique index: Ensure each school has only one active config
CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_configs_unique_active 
ON public.payment_configs(school_id) 
WHERE (is_active = true AND is_deleted = false);

-- Row Level Security (RLS)
ALTER TABLE public.payment_configs ENABLE ROW LEVEL SECURITY;

-- Policies: Schools can only access their own payment configs
DROP POLICY IF EXISTS "Schools can view own payment configs" ON public.payment_configs;
CREATE POLICY "Schools can view own payment configs" ON public.payment_configs
  FOR SELECT USING (school_id = (auth.jwt() ->> 'school_id')::bigint);

DROP POLICY IF EXISTS "Schools can insert own payment configs" ON public.payment_configs;
CREATE POLICY "Schools can insert own payment configs" ON public.payment_configs  
  FOR INSERT WITH CHECK (school_id = (auth.jwt() ->> 'school_id')::bigint);

DROP POLICY IF EXISTS "Schools can update own payment configs" ON public.payment_configs;
CREATE POLICY "Schools can update own payment configs" ON public.payment_configs
  FOR UPDATE USING (school_id = (auth.jwt() ->> 'school_id')::bigint);

-- Function to get payment config for a school
CREATE OR REPLACE FUNCTION get_payment_config(p_school_id BIGINT)
RETURNS TABLE (
  config_id BIGINT,
  mpesa_till_number VARCHAR(20),
  mpesa_paybill VARCHAR(20), 
  mpesa_shortcode VARCHAR(20),
  mpesa_consumer_key TEXT,
  mpesa_consumer_secret TEXT,
  mpesa_passkey TEXT,
  mpesa_environment VARCHAR(20),
  mpesa_base_url VARCHAR(255),
  mpesa_callback_base_url VARCHAR(255),
  paystack_public_key TEXT,
  paystack_secret_key TEXT,
  paystack_environment VARCHAR(20),
  paystack_callback_url VARCHAR(255),
  bank_account_number VARCHAR(50),
  bank_name VARCHAR(100),
  bank_branch VARCHAR(100),
  account_name VARCHAR(200),
  sms_enabled BOOLEAN,
  sms_sender_id VARCHAR(20)
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pc.config_id,
    pc.mpesa_till_number,
    pc.mpesa_paybill,
    pc.mpesa_shortcode,
    pc.mpesa_consumer_key,
    pc.mpesa_consumer_secret,
    pc.mpesa_passkey,
    pc.mpesa_environment,
    pc.mpesa_base_url,
    pc.mpesa_callback_base_url,
    pc.paystack_public_key,
    pc.paystack_secret_key,
    pc.paystack_environment,
    pc.paystack_callback_url,
    pc.bank_account_number,
    pc.bank_name,
    pc.bank_branch,
    pc.account_name,
    pc.sms_enabled,
    pc.sms_sender_id
  FROM public.payment_configs pc
  WHERE pc.school_id = p_school_id
    AND pc.is_active = true
    AND pc.is_deleted = false
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_payment_configs_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER payment_configs_updated_at
  BEFORE UPDATE ON public.payment_configs
  FOR EACH ROW EXECUTE FUNCTION update_payment_configs_timestamp();
