-- EduCore Postgres/Supabase schema
-- Creates ONLY the `report_cards` table (depends on `schools`, `students`).

DO $$
BEGIN
  CREATE TYPE public.report_conduct AS ENUM ('Excellent','Good','Satisfactory','Needs Improvement');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.report_cards (
  report_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id             BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id            BIGINT NOT NULL REFERENCES public.students(student_id),
  term                  VARCHAR(40)  NOT NULL DEFAULT 'Term 2',
  academic_year         VARCHAR(20)  NOT NULL DEFAULT '2026',
  class_name            VARCHAR(60)  NULL,
  total_marks           NUMERIC(8,2) NOT NULL DEFAULT 0,
  average               NUMERIC(5,2) NOT NULL DEFAULT 0,
  class_position        INTEGER NULL,
  out_of                INTEGER NULL,
  class_teacher_comment TEXT NULL,
  principal_comment     TEXT NULL,
  conduct               public.report_conduct NOT NULL DEFAULT 'Good',
  days_present          INTEGER NOT NULL DEFAULT 0,
  days_absent           INTEGER NOT NULL DEFAULT 0,
  is_published          BOOLEAN NOT NULL DEFAULT FALSE,
  generated_at          TIMESTAMPTZ NULL,
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rc
  ON public.report_cards (school_id, student_id, term, academic_year);

