-- EduCore Postgres/Supabase schema
-- Creates ONLY the `guardians` table (depends on `schools`).

DO $$
BEGIN
  CREATE TYPE public.guardian_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.guardians (
  guardian_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         BIGINT NOT NULL REFERENCES public.schools(school_id),
  first_name        VARCHAR(100) NOT NULL,
  last_name         VARCHAR(100) NOT NULL,
  relationship_type VARCHAR(40)  NOT NULL,
  phone             VARCHAR(40)  NULL,
  email             VARCHAR(160) NULL,
  occupation        VARCHAR(120) NULL,
  address           VARCHAR(255) NULL,
  is_primary        BOOLEAN NOT NULL DEFAULT FALSE,
  status            public.guardian_status NOT NULL DEFAULT 'active',
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guardians_school_status
  ON public.guardians (school_id, status);

CREATE INDEX IF NOT EXISTS idx_guardians_deleted
  ON public.guardians (is_deleted);

