-- EduCore Postgres/Supabase schema (Step 2)
-- This file creates ONLY the `users` table (depends on `schools`).
--
-- Notes vs MySQL:
-- - AUTO_INCREMENT -> GENERATED AS IDENTITY
-- - ENUM -> Postgres enum types
-- - DATETIME -> TIMESTAMPTZ
-- - TINYINT(1) -> boolean
-- - MySQL often treats email comparisons as case-insensitive; we use CITEXT to match that behavior.

CREATE EXTENSION IF NOT EXISTS citext;

DO $$
BEGIN
  CREATE TYPE public.user_role AS ENUM ('admin','teacher','finance','hr','librarian','parent','student');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.user_status AS ENUM ('active','inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
  user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id      BIGINT NOT NULL REFERENCES public.schools(school_id),
  student_id     BIGINT NULL,
  full_name      VARCHAR(160) NOT NULL,
  email          CITEXT NOT NULL,
  phone          VARCHAR(40)  NULL,
  password_hash  VARCHAR(255) NOT NULL,
  role           public.user_role NOT NULL,
  status         public.user_status NOT NULL DEFAULT 'active',
  last_login_at  TIMESTAMPTZ NULL,
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Mirrors MySQL: UNIQUE (school_id, email)
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_school_email ON public.users (school_id, email);
CREATE INDEX IF NOT EXISTS idx_users_school_role ON public.users (school_id, role);
CREATE INDEX IF NOT EXISTS idx_users_school_student ON public.users (school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_users_deleted ON public.users (is_deleted);

