import { useState, useEffect } from "react";
import PropTypes from "prop-types";
import Btn from "../components/Btn";
import Field from "../components/Field";
import Badge from "../components/Badge";
import Modal from "../components/Modal";
import { C, inputStyle } from "../lib/theme";
import { apiFetch } from "../lib/api";
import { ALL_CLASSES } from "../lib/constants";

function money(n) { return `KES ${Number(n||0).toLocaleString()}`; }

export default function InvoicesPage({ auth, school, students, canEdit, toast }) {
  const [invoices, setInvoices]       = useState([]);
  const [loading, setLoading]         = useState(true);
  const [showSingle, setShowSingle]   = useState(false);
  const [showBulk, setShowBulk]       = useState(false);
  const [filterStatus, setFilterStatus] = useState("all");
  const [singleForm, setSingleForm]   = useState({ studentId: "", term: "Term 2", academicYear: "2026", tuition: "", activity: "", misc: "", transport: "", dueDate: "" });
  const [singleFormClass, setSingleFormClass] = useState("");
  const [bulkForm, setBulkForm]       = useState({ className: "Grade 7", term: "Term 2", academicYear: "2026", dueDate: "" });

  const load = async () => {
    if (!auth?.token) return;
    try {
      const data = await apiFetch("/invoices", { token: auth.token });
      setInvoices(data);
    } catch (e) { toast(e.message, "error"); }
    setLoading(false);
  };

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [auth]);

  const saveSingle = async () => {
    if (!singleForm.studentId) return toast("Select a student", "error");
    try {
      await apiFetch("/invoices", {
        method: "POST",
        body: { ...singleForm, studentId: Number(singleForm.studentId), tuition: Number(singleForm.tuition)||0, activity: Number(singleForm.activity)||0, misc: Number(singleForm.misc)||0, transport: Number(singleForm.transport)||0 },
        token: auth.token,
      });
      await load(); setShowSingle(false); toast("Invoice created", "success");
    } catch (e) { toast(e.message, "error"); }
  };

  const saveBulk = async () => {
    try {
      const data = await apiFetch("/invoices/bulk", { method: "POST", body: bulkForm, token: auth.token });
      await load(); setShowBulk(false); toast(`${data.created} invoices created`, "success");
    } catch (e) { toast(e.message, "error"); }
  };

  const printInvoice = (inv) => {
    const w = window.open("", "_blank");
    if (!w) {
      toast("Allow pop-ups to print invoices", "error");
      return;
    }
    w.document.write(`
      <html><head><title>Invoice ${inv.invoice_number}</title>
      <style>body{font-family:sans-serif;padding:40px;max-width:500px;margin:auto}h1{font-size:20px;margin-bottom:4px}.school{color:#888;margin-bottom:24px}.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}.total{font-weight:bold;font-size:16px;border-top:2px solid #000;margin-top:8px}@media print{button{display:none}}</style>
      </head><body>
        <h1>Fee Invoice</h1>
        <div class="school">${school?.name || "School"} - ${inv.term} ${inv.academic_year}</div>
        <div class="row"><span>Student</span><strong>${inv.student_name}</strong></div>
        <div class="row"><span>Class</span><strong>${inv.class_name}</strong></div>
        <div class="row"><span>Admission</span><strong>${inv.admission_number}</strong></div>
        <div class="row"><span>Invoice No.</span><strong>${inv.invoice_number}</strong></div>
        <div class="row"><span>Due Date</span><strong>${inv.due_date?.slice(0,10)||'—'}</strong></div>
        <br/>
        <div class="row"><span>Tuition</span><span>${money(inv.tuition)}</span></div>
        <div class="row"><span>Activity</span><span>${money(inv.activity)}</span></div>
        <div class="row"><span>Misc</span><span>${money(inv.misc)}</span></div>
        <div class="row"><span>Transport</span><span>${money(inv.transport)}</span></div>
        <div class="row total"><span>Total</span><span>${money(inv.total)}</span></div>
        <div class="row"><span>Status</span><strong style="text-transform:uppercase">${inv.status}</strong></div>
        <br/><p style="color:#888;font-size:12px">Generated by EduCore School Management System</p>
        <button onclick="window.print()" style="margin-top:16px;padding:8px 16px;cursor:pointer">Print Invoice</button>
      </body></html>
    `);
    w.document.close();
  };

  const filtered = invoices.filter(i => filterStatus === "all" || i.status === filterStatus);
  const totalOwing = invoices.filter(i => i.status !== "paid").reduce((s, i) => s + Number(i.total), 0);

  return (
    <div>
      <div style={{ display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap" }}>
        {[["Total Invoices", invoices.length, "info"], ["Unpaid", invoices.filter(i=>i.status==="unpaid").length, "danger"], ["Partial", invoices.filter(i=>i.status==="partial").length, "warning"], ["Paid", invoices.filter(i=>i.status==="paid").length, "success"]].map(([label, n]) => (
          <div key={label} style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 10, padding: "10px 18px", minWidth: 100 }}>
            <div style={{ fontSize: 22, fontWeight: 800, color: C.text }}>{n}</div>
            <div style={{ fontSize: 12, color: C.textMuted }}>{label}</div>
          </div>
        ))}
        <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 10, padding: "10px 18px" }}>
          <div style={{ fontSize: 18, fontWeight: 800, color: "#ef4444" }}>{money(totalOwing)}</div>
          <div style={{ fontSize: 12, color: C.textMuted }}>Total Owing</div>
        </div>
      </div>

      <div style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>
        <select style={{ ...inputStyle, width: "auto" }} value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
          <option value="all">All</option>
          <option value="unpaid">Unpaid</option>
          <option value="partial">Partial</option>
          <option value="paid">Paid</option>
        </select>
        {canEdit && <Btn onClick={() => setShowSingle(true)}>+ Single Invoice</Btn>}
        {canEdit && <Btn onClick={() => setShowBulk(true)}>📋 Bulk Generate</Btn>}
      </div>

      {loading ? <div style={{ color: C.textMuted, padding: 24 }}>Loading...</div> : (
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>{["Invoice #","Student","Class","Term","Total","Status","Due","Actions"].map(h =>
                <th key={h} style={{ textAlign: "left", padding: "8px 10px", borderBottom: `1px solid ${C.border}`, color: C.textMuted, fontSize: 12 }}>{h}</th>
              )}</tr>
            </thead>
            <tbody>
              {filtered.map(inv => (
                <tr key={inv.invoice_id} style={{ borderBottom: `1px solid ${C.border}` }}>
                  <td style={{ padding: "8px 10px", fontSize: 11, color: C.textMuted }}>{inv.invoice_number}</td>
                  <td style={{ padding: "8px 10px", color: C.text, fontWeight: 600 }}>{inv.student_name}</td>
                  <td style={{ padding: "8px 10px", color: C.textSub }}>{inv.class_name}</td>
                  <td style={{ padding: "8px 10px", color: C.textMuted }}>{inv.term}</td>
                  <td style={{ padding: "8px 10px", color: C.text, fontWeight: 600 }}>{money(inv.total)}</td>
                  <td style={{ padding: "8px 10px" }}><Badge text={inv.status} tone={inv.status==="paid"?"success":inv.status==="partial"?"warning":"danger"} /></td>
                  <td style={{ padding: "8px 10px", color: C.textMuted, fontSize: 12 }}>{inv.due_date?.slice(0,10)||"—"}</td>
                  <td style={{ padding: "8px 10px" }}><Btn variant="ghost" onClick={() => printInvoice(inv)}>🖨 Print</Btn></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {showSingle && (
        <Modal title="Create Invoice" onClose={() => setShowSingle(false)}>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
            <Field label="Class" style={{ gridColumn: "1 / -1" }}>
              <select style={inputStyle} value={singleFormClass} onChange={e => { setSingleFormClass(e.target.value); setSingleForm({ ...singleForm, studentId: "" }); }}>
                <option value="">-- Select class first --</option>
                {ALL_CLASSES.map(c => <option key={c}>{c}</option>)}
              </select>
            </Field>
            <Field label="Student" style={{ gridColumn: "1 / -1" }}>
              <select style={inputStyle} value={singleForm.studentId} onChange={e => setSingleForm({ ...singleForm, studentId: e.target.value })} disabled={!singleFormClass}>
                <option value="">{singleFormClass ? "-- Select student --" : "-- Select class first --"}</option>
                {students.filter(s => (s.className ?? s.class_name) === singleFormClass).map(s => { const id = s.id ?? s.student_id; const name = s.firstName ? `${s.firstName} ${s.lastName}` : `${s.first_name} ${s.last_name}`; return <option key={id} value={id}>{name}</option>; })}
              </select>
            </Field>
            <Field label="Term"><select style={inputStyle} value={singleForm.term} onChange={e => setSingleForm({ ...singleForm, term: e.target.value })}><option>Term 1</option><option>Term 2</option><option>Term 3</option></select></Field>
            <Field label="Academic Year"><input style={inputStyle} value={singleForm.academicYear} onChange={e => setSingleForm({ ...singleForm, academicYear: e.target.value })} /></Field>
            <Field label="Tuition (KES)"><input type="number" style={inputStyle} value={singleForm.tuition} onChange={e => setSingleForm({ ...singleForm, tuition: e.target.value })} /></Field>
            <Field label="Activity (KES)"><input type="number" style={inputStyle} value={singleForm.activity} onChange={e => setSingleForm({ ...singleForm, activity: e.target.value })} /></Field>
            <Field label="Misc (KES)"><input type="number" style={inputStyle} value={singleForm.misc} onChange={e => setSingleForm({ ...singleForm, misc: e.target.value })} /></Field>
            <Field label="Transport (KES)"><input type="number" style={inputStyle} value={singleForm.transport} onChange={e => setSingleForm({ ...singleForm, transport: e.target.value })} /></Field>
            <Field label="Due Date"><input type="date" style={inputStyle} value={singleForm.dueDate} onChange={e => setSingleForm({ ...singleForm, dueDate: e.target.value })} /></Field>
          </div>
          <div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 12 }}>
            <Btn variant="ghost" onClick={() => setShowSingle(false)}>Cancel</Btn>
            <Btn onClick={saveSingle}>Create Invoice</Btn>
          </div>
        </Modal>
      )}

      {showBulk && (
        <Modal title="Bulk Generate Invoices" onClose={() => setShowBulk(false)}>
          <div style={{ color: C.textSub, fontSize: 13, marginBottom: 12 }}>
            Generates invoices for all students in a class using the existing fee structure.
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
            <Field label="Class"><select style={inputStyle} value={bulkForm.className} onChange={e => setBulkForm({ ...bulkForm, className: e.target.value })}>{ALL_CLASSES.map(c => <option key={c}>{c}</option>)}</select></Field>
            <Field label="Term"><select style={inputStyle} value={bulkForm.term} onChange={e => setBulkForm({ ...bulkForm, term: e.target.value })}><option>Term 1</option><option>Term 2</option><option>Term 3</option></select></Field>
            <Field label="Academic Year"><input style={inputStyle} value={bulkForm.academicYear} onChange={e => setBulkForm({ ...bulkForm, academicYear: e.target.value })} /></Field>
            <Field label="Due Date"><input type="date" style={inputStyle} value={bulkForm.dueDate} onChange={e => setBulkForm({ ...bulkForm, dueDate: e.target.value })} /></Field>
          </div>
          <div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 12 }}>
            <Btn variant="ghost" onClick={() => setShowBulk(false)}>Cancel</Btn>
            <Btn onClick={saveBulk}>Generate All</Btn>
          </div>
        </Modal>
      )}
    </div>
  );
}

InvoicesPage.propTypes = {
  auth: PropTypes.object,
  school: PropTypes.object,
  students: PropTypes.array.isRequired,
  canEdit: PropTypes.bool.isRequired,
  toast: PropTypes.func.isRequired,
};
