CREATE TABLE IF NOT EXISTS public.expenditures (
  expenditure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL REFERENCES public.schools(school_id),
  expense_date DATE NOT NULL,
  category VARCHAR(80) NOT NULL,
  item_name VARCHAR(180) NOT NULL,
  description TEXT NULL,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(40) NOT NULL DEFAULT 'cash',
  vendor_name VARCHAR(180) NULL,
  paid_to_name VARCHAR(180) NULL,
  purpose VARCHAR(255) NULL,
  reference_number VARCHAR(120) NULL,
  notes TEXT NULL,
  created_by BIGINT NULL,
  released_by_user_id BIGINT NULL,
  released_by_name VARCHAR(180) NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_expenditures_school_date
  ON public.expenditures (school_id, expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_expenditures_school_category
  ON public.expenditures (school_id, category);
