-- Migration: Create HR tables
-- This migration creates the HR tables for staff management

-- Create enum types if they don't exist
DO $$
BEGIN
  CREATE TYPE public.hr_contract_type AS ENUM ('Permanent','Contract','Part-time','Volunteer');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.hr_staff_status AS ENUM ('active','inactive','on-leave');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.hr_leave_status AS ENUM ('pending','approved','rejected');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.hr_attendance_status AS ENUM ('present','absent','late','half-day','on-leave');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.hr_payslip_status AS ENUM ('draft','approved','paid');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create hr_staff table
CREATE TABLE IF NOT EXISTS public.hr_staff (
  staff_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     BIGINT NOT NULL REFERENCES public.schools(school_id),
  full_name     VARCHAR(200) NOT NULL,
  email         VARCHAR(160) NULL,
  phone         VARCHAR(40)  NULL,
  national_id   VARCHAR(40)  NULL,
  department    VARCHAR(100) NOT NULL DEFAULT 'Academic',
  job_title     VARCHAR(100) NOT NULL,
  contract_type public.hr_contract_type NOT NULL DEFAULT 'Permanent',
  start_date    DATE NULL,
  salary        NUMERIC(12,2) NOT NULL DEFAULT 0,
  status        public.hr_staff_status NOT NULL DEFAULT 'active',
  notes         TEXT NULL,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create hr_leave table
CREATE TABLE IF NOT EXISTS public.hr_leave (
  leave_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id  BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id   BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  leave_type VARCHAR(60) NOT NULL DEFAULT 'Annual',
  from_date  DATE NOT NULL,
  to_date    DATE NOT NULL,
  reason     TEXT NULL,
  status     public.hr_leave_status NOT NULL DEFAULT 'pending',
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create hr_attendance table
CREATE TABLE IF NOT EXISTS public.hr_attendance (
  hr_attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id         BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  attendance_date  DATE NOT NULL,
  check_in         TIME NULL,
  check_out        TIME NULL,
  status           public.hr_attendance_status NOT NULL DEFAULT 'present',
  notes            TEXT NULL,
  marked_by        BIGINT NULL,
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_att
  ON public.hr_attendance (school_id, staff_id, attendance_date);

-- Create hr_payslips table
CREATE TABLE IF NOT EXISTS public.hr_payslips (
  payslip_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    BIGINT NOT NULL REFERENCES public.schools(school_id),
  staff_id     BIGINT NOT NULL REFERENCES public.hr_staff(staff_id),
  month        SMALLINT NOT NULL,
  year         SMALLINT NOT NULL,
  basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
  allowances   NUMERIC(12,2) NOT NULL DEFAULT 0,
  deductions   NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_pay      NUMERIC(12,2) NOT NULL DEFAULT 0,
  paye         NUMERIC(12,2) NOT NULL DEFAULT 0,
  nhif         NUMERIC(12,2) NOT NULL DEFAULT 0,
  nssf         NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes        TEXT NULL,
  status       public.hr_payslip_status NOT NULL DEFAULT 'draft',
  paid_date    DATE NULL,
  generated_by BIGINT NULL,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payslip
  ON public.hr_payslips (school_id, staff_id, month, year);

-- Add RLS policies for tenant isolation
ALTER TABLE public.hr_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_leave ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_payslips ENABLE ROW LEVEL SECURITY;

-- Policy for hr_staff
CREATE POLICY tenant_isolation_hr_staff
  ON public.hr_staff
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id)
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY select_hr_staff_school
  ON public.hr_staff FOR SELECT
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY insert_hr_staff_school
  ON public.hr_staff FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY update_hr_staff_school
  ON public.hr_staff FOR UPDATE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY delete_hr_staff_school
  ON public.hr_staff FOR DELETE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

-- Policy for hr_leave
CREATE POLICY tenant_isolation_hr_leave
  ON public.hr_leave
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id)
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY select_hr_leave_school
  ON public.hr_leave FOR SELECT
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY insert_hr_leave_school
  ON public.hr_leave FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY update_hr_leave_school
  ON public.hr_leave FOR UPDATE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY delete_hr_leave_school
  ON public.hr_leave FOR DELETE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

-- Policy for hr_attendance
CREATE POLICY tenant_isolation_hr_attendance
  ON public.hr_attendance
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id)
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY select_hr_attendance_school
  ON public.hr_attendance FOR SELECT
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY insert_hr_attendance_school
  ON public.hr_attendance FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY update_hr_attendance_school
  ON public.hr_attendance FOR UPDATE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY delete_hr_attendance_school
  ON public.hr_attendance FOR DELETE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

-- Policy for hr_payslips
CREATE POLICY tenant_isolation_hr_payslips
  ON public.hr_payslips
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id)
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY select_hr_payslips_school
  ON public.hr_payslips FOR SELECT
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY insert_hr_payslips_school
  ON public.hr_payslips FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY update_hr_payslips_school
  ON public.hr_payslips FOR UPDATE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);

CREATE POLICY delete_hr_payslips_school
  ON public.hr_payslips FOR DELETE
  USING ((auth.jwt() ->> 'school_id')::bigint = school_id);
