-- Create teacher_class_assignments table to match backend code expectations
-- This table is used by teacherassignments.routes.js and getTeacherClasses.js

CREATE TABLE IF NOT EXISTS public.teacher_class_assignments (
  assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL REFERENCES public.schools(school_id),
  teacher_id BIGINT NOT NULL REFERENCES public.users(user_id),
  class_id BIGINT REFERENCES public.classes(class_id),
  class_name VARCHAR(80) NOT NULL,
  subject_id BIGINT REFERENCES public.subjects(subject_id),
  subject_name VARCHAR(100),
  is_class_teacher BOOLEAN NOT NULL DEFAULT FALSE,
  academic_year VARCHAR(10),
  term VARCHAR(50),
  assigned_by BIGINT REFERENCES public.users(user_id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_teacher_class_assignments_school_teacher 
  ON public.teacher_class_assignments(school_id, teacher_id);
  
CREATE INDEX IF NOT EXISTS idx_teacher_class_assignments_school_class 
  ON public.teacher_class_assignments(school_id, class_id);

CREATE INDEX IF NOT EXISTS idx_teacher_class_assignments_active 
  ON public.teacher_class_assignments(is_active);

-- Enable RLS
ALTER TABLE public.teacher_class_assignments ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Teachers can view own assignments" 
  ON public.teacher_class_assignments FOR SELECT 
  USING (school_id = (SELECT school_id FROM auth.users WHERE id = auth.uid()));

CREATE POLICY "Admins can view all assignments" 
  ON public.teacher_class_assignments FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE id = auth.uid() 
      AND school_id = public.teacher_class_assignments.school_id 
      AND role IN ('admin', 'director', 'superadmin')
    )
  );

CREATE POLICY "Admins can insert assignments" 
  ON public.teacher_class_assignments FOR INSERT 
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE id = auth.uid() 
      AND school_id = public.teacher_class_assignments.school_id 
      AND role IN ('admin', 'director', 'superadmin')
    )
  );

CREATE POLICY "Admins can update assignments" 
  ON public.teacher_class_assignments FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE id = auth.uid() 
      AND school_id = public.teacher_class_assignments.school_id 
      AND role IN ('admin', 'director', 'superadmin')
    )
  );
