-- Missing Finance Tables for EduCore
-- Run this in Supabase SQL Editor to create any missing finance-related tables
-- This script is idempotent (uses IF NOT EXISTS)

-- =====================================================
-- CHART OF ACCOUNTS (for double-entry accounting)
-- =====================================================
CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id BIGINT NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    account_name VARCHAR(200) NOT NULL,
    account_type VARCHAR(50) NOT NULL, -- asset, liability, equity, revenue, expense
    account_subtype VARCHAR(50),
    normal_balance VARCHAR(10) DEFAULT 'debit', -- debit or credit
    parent_account_id UUID REFERENCES chart_of_accounts(id),
    is_active BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(school_id, account_code)
);

CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_school ON chart_of_accounts(school_id);
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_type ON chart_of_accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_parent ON chart_of_accounts(parent_account_id);

-- =====================================================
-- JOURNAL ENTRIES (for double-entry accounting)
-- =====================================================
CREATE TABLE IF NOT EXISTS journal_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id BIGINT NOT NULL,
    entry_number VARCHAR(50) NOT NULL,
    entry_date DATE NOT NULL,
    reference_type VARCHAR(50), -- invoice, payment, receipt, etc.
    reference_id UUID,
    description TEXT,
    status VARCHAR(20) DEFAULT 'posted', -- draft, posted, void
    total_debit DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_credit DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_by UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(school_id, entry_number)
);

CREATE INDEX IF NOT EXISTS idx_journal_entries_school ON journal_entries(school_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_date ON journal_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_journal_entries_reference ON journal_entries(reference_type, reference_id);

-- =====================================================
-- JOURNAL ENTRY LINES (for double-entry accounting)
-- =====================================================
CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    journal_entry_id UUID NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_id UUID NOT NULL REFERENCES chart_of_accounts(id),
    debit DECIMAL(15,2) NOT NULL DEFAULT 0,
    credit DECIMAL(15,2) NOT NULL DEFAULT 0,
    description TEXT,
    line_number INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_entry ON journal_entry_lines(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_account ON journal_entry_lines(account_id);

-- =====================================================
-- STUDENT LEDGER (legacy fee balance tracking)
-- =====================================================
CREATE TABLE IF NOT EXISTS student_ledger (
    ledger_id BIGSERIAL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('charge','payment','adjustment','carry_forward','waiver')),
    amount DECIMAL(12,2) NOT NULL,
    balance_after DECIMAL(12,2) NOT NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    description TEXT NULL,
    receipt_number VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ledger_student ON student_ledger(school_id, student_id);
CREATE INDEX IF NOT EXISTS idx_ledger_receipt ON student_ledger(receipt_number);
CREATE INDEX IF NOT EXISTS idx_ledger_transaction ON student_ledger(transaction_type, created_at);
CREATE INDEX IF NOT EXISTS idx_ledger_reference ON student_ledger(reference_type, reference_id);

ALTER TABLE student_ledger ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- FEE BALANCE LEDGER (new system - parallel to invoices)
-- =====================================================
CREATE TABLE IF NOT EXISTS fee_balance_ledger (
    ledger_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT NOT NULL REFERENCES schools(school_id),
    student_id         BIGINT NOT NULL REFERENCES students(student_id),
    academic_year_id   BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
    term_id            BIGINT REFERENCES terms(term_id),
    transaction_type   VARCHAR(20) NOT NULL
                        CHECK (transaction_type IN ('charge', 'payment', 'carry_forward', 'waiver', 'adjustment')),
    transaction_date   DATE NOT NULL,
    amount             NUMERIC(12,2) NOT NULL, -- Positive for charges, negative for payments
    balance_before     NUMERIC(12,2) NOT NULL,
    balance_after      NUMERIC(12,2) NOT NULL,
    reference_type     VARCHAR(20) NOT NULL
                        CHECK (reference_type IN ('invoice', 'payment', 'manual', 'journal_entry')),
    reference_id       BIGINT NOT NULL, -- Links to invoices.id or payments.id or journal_entries.id
    description        TEXT,
    created_by         BIGINT REFERENCES users(user_id),
    is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fee_ledger_student
  ON fee_balance_ledger (student_id, transaction_date) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_fee_ledger_school_year_term
  ON fee_balance_ledger (school_id, academic_year_id, term_id) WHERE NOT is_deleted;

-- =====================================================
-- PAYMENT PLANS (for installment payment arrangements)
-- =====================================================
CREATE TABLE IF NOT EXISTS payment_plans (
    plan_id BIGSERIAL PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(school_id),
    student_id BIGINT NOT NULL REFERENCES students(student_id),
    invoice_id BIGINT NULL REFERENCES invoices(invoice_id),
    total_amount DECIMAL(12,2) NOT NULL,
    installment_count INTEGER NOT NULL DEFAULT 2,
    start_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
    created_by BIGINT REFERENCES users(user_id),
    approved_by BIGINT REFERENCES users(user_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_plans_school_student
  ON payment_plans (school_id, student_id) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_payment_plans_status
  ON payment_plans (status) WHERE NOT is_deleted;

-- =====================================================
-- DISCOUNT CONFIGS (school-wide discount settings)
-- =====================================================
CREATE TABLE IF NOT EXISTS discount_configs (
    config_id SERIAL PRIMARY KEY,
    school_id INTEGER NOT NULL REFERENCES schools(school_id),
    discount_type VARCHAR(30) NOT NULL,
    -- Types: sibling_2nd, sibling_3rd, sibling_4th_plus, staff_child, custom, scholarship, bursary
    discount_value DECIMAL(5,2) NOT NULL DEFAULT 0,
    -- Percentage (0-100)
    is_active BOOLEAN DEFAULT true,
    created_by INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(school_id, discount_type)
);

-- =====================================================
-- STUDENT DISCOUNTS (individual discount assignments)
-- =====================================================
CREATE TABLE IF NOT EXISTS student_discounts (
    discount_id SERIAL PRIMARY KEY,
    school_id INTEGER NOT NULL REFERENCES schools(school_id),
    student_id INTEGER NOT NULL REFERENCES students(student_id),
    discount_type VARCHAR(30) NOT NULL,
    discount_value DECIMAL(5,2) NOT NULL,
    -- Actual % applied to this student
    discount_value_type VARCHAR(10) NOT NULL DEFAULT 'percentage', -- 'percentage' or 'fixed'
    discount_amount DECIMAL(10,2),
    -- Actual KES amount saved (calculated on fee generation)
    reason TEXT,
    is_active BOOLEAN DEFAULT true,
    approved_by INTEGER REFERENCES users(user_id),
    approved_at TIMESTAMP,
    starts_at DATE DEFAULT CURRENT_DATE,
    expires_at DATE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_student_discounts_student
  ON student_discounts(student_id, school_id)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_discount_configs_school
  ON discount_configs(school_id, discount_type)
  WHERE is_active = true;

-- =====================================================
-- ROLE PERMISSIONS (for access control)
-- =====================================================
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGSERIAL PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(school_id),
    role_name VARCHAR(50) NOT NULL,
    can_edit BOOLEAN NOT NULL DEFAULT FALSE,
    pages_json JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(school_id, role_name)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_school ON role_permissions(school_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role_name);

-- =====================================================
-- ACTIVITY LOGS (for audit trail)
-- =====================================================
CREATE TABLE IF NOT EXISTS activity_logs (
    log_id BIGSERIAL PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(school_id),
    user_id BIGINT NULL REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NULL,
    entity_id BIGINT NULL,
    description TEXT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    metadata JSONB NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_school ON activity_logs(school_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_entity ON activity_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- DEFAULT DATA SEEDING
-- =====================================================

-- Seed default discount configs for all schools
INSERT INTO discount_configs (school_id, discount_type, discount_value, is_active)
SELECT 
    school_id,
    discount_type,
    discount_value,
    true
FROM (
    VALUES
        (1, 'sibling_2nd', 10),
        (1, 'sibling_3rd', 20),
        (1, 'sibling_4th_plus', 30),
        (1, 'staff_child', 50),
        (1, 'scholarship', 100),
        (1, 'bursary', 50)
) AS defaults(school_id, discount_type, discount_value)
WHERE NOT EXISTS (
    SELECT 1 FROM discount_configs 
    WHERE discount_configs.school_id = defaults.school_id 
    AND discount_configs.discount_type = defaults.discount_type
);

-- Seed default role permissions for all schools
INSERT INTO role_permissions (school_id, role_name, can_edit, pages_json)
SELECT 
    school_id,
    role_name,
    can_edit,
    pages_json
FROM (
    VALUES
        (1, 'superadmin', true, '["*"]'::jsonb),
        (1, 'director', true, '["dashboard","students","staff","attendance","grades","subjects","fees","expenditures","admissions","invoices","reportcards","discipline","transport","announcements","lesson-plans","exams","library","analysis","activity-logs","branches","admin-permissions","performance","promotion","notifications","discounts","financial-reports","trial-balance","income-statement","chart-of-accounts","journal-entries","general-ledger","balance-sheet"]'::jsonb),
        (1, 'admin', true, '["dashboard","students","staff","attendance","grades","subjects","fees","expenditures","admissions","invoices","reportcards","discipline","transport","announcements","lesson-plans","exams","library","analysis","financial-reports","trial-balance","income-statement","chart-of-accounts","journal-entries","general-ledger","balance-sheet"]'::jsonb),
        (1, 'finance', true, '["dashboard","students","fees","invoices","expenditures","financial-reports","trial-balance","income-statement","chart-of-accounts","journal-entries","general-ledger","balance-sheet","discounts"]'::jsonb),
        (1, 'teacher', false, '["dashboard","students","attendance","grades","subjects","lesson-plans","exams","library"]'::jsonb),
        (1, 'parent', false, '["dashboard","students","attendance","grades","reportcards","fees","announcements"]'::jsonb),
        (1, 'student', false, '["dashboard","attendance","grades","reportcards","fees","announcements","library"]'::jsonb)
) AS default_perms(school_id, role_name, can_edit, pages_json)
WHERE NOT EXISTS (
    SELECT 1 FROM role_permissions 
    WHERE role_permissions.school_id = default_perms.school_id 
    AND role_permissions.role_name = default_perms.role_name
);

-- =====================================================
-- COMMENTS
-- =====================================================
COMMENT ON TABLE chart_of_accounts IS 'Chart of accounts for double-entry bookkeeping';
COMMENT ON TABLE journal_entries IS 'Journal entries for double-entry accounting';
COMMENT ON TABLE journal_entry_lines IS 'Individual lines within journal entries';
COMMENT ON TABLE student_ledger IS 'Legacy student fee ledger tracking balances';
COMMENT ON TABLE fee_balance_ledger IS 'New student fee balance ledger - parallel to invoices';
COMMENT ON TABLE payment_plans IS 'Installment payment plans for students';
COMMENT ON TABLE discount_configs IS 'School-wide discount percentage configurations';
COMMENT ON TABLE student_discounts IS 'Individual student discount assignments';
COMMENT ON TABLE role_permissions IS 'Role-based permissions per school';
COMMENT ON TABLE activity_logs IS 'System activity audit log';

-- =====================================================
-- ROLLBACK (if needed)
-- =====================================================
-- DROP TABLE IF EXISTS activity_logs CASCADE;
-- DROP TABLE IF EXISTS role_permissions CASCADE;
-- DROP TABLE IF EXISTS student_discounts CASCADE;
-- DROP TABLE IF EXISTS discount_configs CASCADE;
-- DROP TABLE IF EXISTS payment_plans CASCADE;
-- DROP TABLE IF EXISTS fee_balance_ledger CASCADE;
-- DROP TABLE IF EXISTS student_ledger CASCADE;
-- DROP TABLE IF EXISTS journal_entry_lines CASCADE;
-- DROP TABLE IF EXISTS journal_entries CASCADE;
-- DROP TABLE IF EXISTS chart_of_accounts CASCADE;
