-- Phase 6A: Enterprise Security Migration

-- 1. Add security_settings JSONB to schools if it does not exist
ALTER TABLE public.schools 
ADD COLUMN IF NOT EXISTS security_settings JSONB DEFAULT '{
  "passwordPolicy": {
    "minLength": 8,
    "requireUppercase": true,
    "requireLowercase": true,
    "requireNumber": true,
    "requireSymbol": false,
    "expiryDays": 0,
    "preventReuse": 5
  },
  "lockout": {
    "maxFailedAttempts": 5,
    "lockoutDurationMinutes": 15
  }
}'::jsonb;

-- 2. Create trusted_devices table
CREATE TABLE IF NOT EXISTS public.trusted_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  school_id BIGINT NOT NULL REFERENCES public.schools(school_id) ON DELETE CASCADE,
  device_hash VARCHAR(255) NOT NULL,
  device_name VARCHAR(255) NULL,
  browser VARCHAR(100) NULL,
  operating_system VARCHAR(100) NULL,
  last_ip VARCHAR(45) NULL,
  last_login TIMESTAMPTZ NULL,
  last_used TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  trusted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, device_hash)
);

CREATE INDEX IF NOT EXISTS idx_trusted_devices_user ON public.trusted_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_trusted_devices_school ON public.trusted_devices(school_id);

-- RLS policies for trusted_devices
ALTER TABLE public.trusted_devices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own trusted devices" ON public.trusted_devices
  FOR ALL
  USING (user_id = (auth.jwt() ->> 'user_id')::bigint)
  WITH CHECK (user_id = (auth.jwt() ->> 'user_id')::bigint);
